-- Generated by scripts/build-noop-check.mjs from 00014_complete_order_checklist.sql. Do not edit by hand.
--
-- Confirms 00014 is a safe no-op on the current live database.
--
-- 00014 inserts 20 orders with generated uuid primary keys and
-- `on conflict (name) do nothing`. The conflict target is `name`, not `id`,
-- so a re-run must match on the unique name index, skip every row, and leave
-- existing ids alone. Running it in a transaction and rolling back proves that
-- without writing anything.
--
-- Paste into the Supabase SQL editor. Expect: NO-OP-OK

begin;

create temporary table orders_before as
  select id, name from public.taxonomic_orders;

insert into public.taxonomic_orders (name, common_name, description) values
  ('Archaeognatha',      'Bristletails',
   'Primitive wingless insects that leap and are found on damp rock near streams. Includes jumping bristletails.'),
  ('Zygentoma',         'Silverfish and firebrats',
   'Wingless scavengers of damp organic matter that nibble starch in books, wallpaper and stored grain.'),
  ('Ephemeroptera',     'Mayflies',
   'Aquatic nymphs with feathered or plate-like gills; the short-lived winged adults are a vital fish food source.'),
  ('Odonata',           'Dragonflies and damselflies',
   'Nymphs are aquatic predators; adults are aggressive hunters of flying insects and are strong indicators of clean water.'),
  ('Plecoptera',        'Stoneflies',
   'Aquatic nymphs that need well-oxygenated water, so they signal unpolluted streams. Adults are short-lived and weak fliers.'),
  ('Dermaptera',        'Earwigs',
   'Forceps-like pincers at the abdomen tip. Omnivorous scavengers that can become minor pests of soft fruit and seedlings.'),
  ('Zoraptera',         'Angel insects',
   'Tiny, gregarious, wingless or dimorphic insects living in leaf litter and damp decaying wood.'),
  ('Mantodea',          'Praying mantises',
   'Raptorial predators of insects including crop pests, making them beneficial generalists in field vegetation.'),
  ('Blattodea',         'Cockroaches and termites',
   'Includes the termites, the most damaging insect group on crops worldwide, plus the omnivorous cockroaches.'),
  ('Grylloblattodea',   'Rock crawlers',
   'Rare, cold-adapted chewing insects restricted to high mountains and glacier margins; effectively never pests of crops.'),
  ('Mantophasmatodea',  'Gladiator insects',
   'A small order from southern Africa whose members both ambush prey and show parental care, earning the name "gladiator".'),
  ('Phasmatodea',       'Stick and leaf insects',
   'Camouflaged herbivores that feed on foliage. Heavily defended with chemical secretions and mimicry rather than speed.'),
  ('Embioptera',        'Webspinners',
   'Spin silk galleries in silk from glands on the front legs; live in colonies in leaf litter and bark crevices.'),
  ('Psocodea',          'Barklice, booklice and parasitic lice',
   'A merged order: free-living barklice that graze algae and fungi, plus the parasitic sucking and chewing lice.'),
  ('Megaloptera',       'Alderflies, dobsonflies and fishflies',
   'Large soft-bodied aquatic larvae; the dobsonfly larvae are hellgrammites. Adults are short-lived and feed little.'),
  ('Raphidioptera',     'Snakeflies',
   'Predatory insects with a long flexible neck used to grab prey, mainly predators of soft-bodied arthropods.'),
  ('Mecoptera',         'Scorpionflies and hangingflies',
   'Distinctive elongated beak-like mouthparts; includes the Mecoptera sensu lato group alongside fleas and lacewings.'),
  ('Siphonaptera',      'Fleas',
   'Laterally flattened, wingless, jumping blood-sucking ectoparasites of mammals, vectors of plague and tapeworms.'),
  ('Trichoptera',       'Caddisflies',
   'Caddisfly larvae are aquatic and build cases of sand, silk or plant debris; used as clean-water indicators.'),
  ('Strepsiptera',      'Twisted-wing parasites',
   'Highly specialised endoparasites, males emerge twisted-winged to mate. Rarely observed as free-living adults.')
on conflict (name) do nothing;

-- A correct no-op: nothing added, no id changed.
select
  count(*) filter (where b.id is null) as rows_added,
  count(*) filter (where b.id is distinct from a.id) as ids_changed,
  (select count(*) from public.taxonomic_orders) as orders_now,
  case
    when count(*) filter (where b.id is null) = 0
     and count(*) filter (where b.id is distinct from a.id) = 0
    then 'NO-OP-OK'
    else 'MIGRATED - inspect before committing'
  end as verdict
from orders_before b
full join public.taxonomic_orders a on a.name = b.name;

rollback;

select 'rolled back; live data unchanged' as note;
