-- Life-cycle stage illustrations.
--
-- Generated by scripts/generate-lifecycle-illustrations.mjs. Do not edit by hand;
-- rerun the generator instead so the paths stay in step with the SVG files in
-- public/lifecycle-stages.
--
-- These are first-party diagrams served as static assets, not photographs in the
-- insect-images storage bucket, so the values are root-relative asset paths and
-- deliberately do not go through useImageUrl.
--
-- Idempotent: each statement re-sets the same value, so re-running is safe.

update public.life_cycles lc
   set image_url = '/lifecycle-stages/bemisia-tabaci-egg.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Bemisia tabaci'
   and lc.stage_name = 'egg';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/bemisia-tabaci-nymph.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Bemisia tabaci'
   and lc.stage_name = 'nymph';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/bemisia-tabaci-pupa.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Bemisia tabaci'
   and lc.stage_name = 'pupa';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/bemisia-tabaci-adult.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Bemisia tabaci'
   and lc.stage_name = 'adult';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/aphis-gossypii-nymph.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Aphis gossypii'
   and lc.stage_name = 'nymph';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/aphis-gossypii-adult.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Aphis gossypii'
   and lc.stage_name = 'adult';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/helicoverpa-armigera-egg.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Helicoverpa armigera'
   and lc.stage_name = 'egg';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/helicoverpa-armigera-larva.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Helicoverpa armigera'
   and lc.stage_name = 'larva';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/helicoverpa-armigera-pupa.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Helicoverpa armigera'
   and lc.stage_name = 'pupa';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/helicoverpa-armigera-adult.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Helicoverpa armigera'
   and lc.stage_name = 'adult';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/spodoptera-frugiperda-egg.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Spodoptera frugiperda'
   and lc.stage_name = 'egg';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/spodoptera-frugiperda-larva.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Spodoptera frugiperda'
   and lc.stage_name = 'larva';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/spodoptera-frugiperda-pupa.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Spodoptera frugiperda'
   and lc.stage_name = 'pupa';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/spodoptera-frugiperda-adult.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Spodoptera frugiperda'
   and lc.stage_name = 'adult';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/pectinophora-gossypiella-egg.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Pectinophora gossypiella'
   and lc.stage_name = 'egg';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/pectinophora-gossypiella-larva.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Pectinophora gossypiella'
   and lc.stage_name = 'larva';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/pectinophora-gossypiella-pupa.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Pectinophora gossypiella'
   and lc.stage_name = 'pupa';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/pectinophora-gossypiella-adult.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Pectinophora gossypiella'
   and lc.stage_name = 'adult';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/leucinodes-orbonalis-egg.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Leucinodes orbonalis'
   and lc.stage_name = 'egg';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/leucinodes-orbonalis-larva.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Leucinodes orbonalis'
   and lc.stage_name = 'larva';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/leucinodes-orbonalis-pupa.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Leucinodes orbonalis'
   and lc.stage_name = 'pupa';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/leucinodes-orbonalis-adult.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Leucinodes orbonalis'
   and lc.stage_name = 'adult';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/coccinella-septempunctata-egg.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Coccinella septempunctata'
   and lc.stage_name = 'egg';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/coccinella-septempunctata-larva.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Coccinella septempunctata'
   and lc.stage_name = 'larva';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/coccinella-septempunctata-pupa.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Coccinella septempunctata'
   and lc.stage_name = 'pupa';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/coccinella-septempunctata-adult.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Coccinella septempunctata'
   and lc.stage_name = 'adult';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/thrips-tabaci-egg.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Thrips tabaci'
   and lc.stage_name = 'egg';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/thrips-tabaci-nymph.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Thrips tabaci'
   and lc.stage_name = 'nymph';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/thrips-tabaci-pupa.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Thrips tabaci'
   and lc.stage_name = 'pupa';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/thrips-tabaci-adult.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Thrips tabaci'
   and lc.stage_name = 'adult';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/nilaparvata-lugens-nymph.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Nilaparvata lugens'
   and lc.stage_name = 'nymph';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/nilaparvata-lugens-adult.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Nilaparvata lugens'
   and lc.stage_name = 'adult';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/chrysoperla-carnea-egg.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Chrysoperla carnea'
   and lc.stage_name = 'egg';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/chrysoperla-carnea-larva.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Chrysoperla carnea'
   and lc.stage_name = 'larva';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/chrysoperla-carnea-pupa.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Chrysoperla carnea'
   and lc.stage_name = 'pupa';

update public.life_cycles lc
   set image_url = '/lifecycle-stages/chrysoperla-carnea-adult.svg'
  from public.insects i
 where i.id = lc.insect_id
   and i.scientific_name = 'Chrysoperla carnea'
   and lc.stage_name = 'adult';
